
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:19111/
    username: postgres
    password: "postgres"
    database: "postgres"
    driverClassname: org.postgresql.Driver